namespace FlyOutApp;

// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
// If you change the class to 'public' in order to use it outside its assembly
//  you should also change the fields from 'const' to 'public static readonly'
static class IconFont //Flowery.ttf
{
	public const string LF = "\u000a";
	public const string ControlCR = "\u000d";
	public const string Space = "\u0020";
	public const string A = "\u0041";
	public const string B = "\u0042";
	public const string C = "\u0043";
	public const string D = "\u0044";
	public const string E = "\u0045";
	public const string F = "\u0046";
	public const string G = "\u0047";
	public const string H = "\u0048";
	public const string I = "\u0049";
	public const string J = "\u004a";
	public const string K = "\u004b";
	public const string L = "\u004c";
	public const string M = "\u004d";
	public const string N = "\u004e";
	public const string O = "\u004f";
	public const string P = "\u0050";
	public const string Q = "\u0051";
	public const string R = "\u0052";
	public const string S = "\u0053";
	public const string T = "\u0054";
	public const string U = "\u0055";
	public const string V = "\u0056";
	public const string W = "\u0057";
	public const string X = "\u0058";
	public const string Y = "\u0059";
	public const string Z = "\u005a";
	public const string a = "\u0061";
	public const string b = "\u0062";
	public const string c = "\u0063";
	public const string d = "\u0064";
	public const string e = "\u0065";
	public const string f = "\u0066";
	public const string g = "\u0067";
	public const string h = "\u0068";
	public const string i = "\u0069";
	public const string j = "\u006a";
	public const string k = "\u006b";
	public const string l = "\u006c";
	public const string m = "\u006d";
	public const string n = "\u006e";
	public const string o = "\u006f";
	public const string p = "\u0070";
	public const string q = "\u0071";
	public const string r = "\u0072";
	public const string s = "\u0073";
	public const string t = "\u0074";
	public const string u = "\u0075";
	public const string v = "\u0076";
	public const string w = "\u0077";
	public const string x = "\u0078";
	public const string y = "\u0079";
	public const string z = "\u007a";
	public const string Nonbreakingspace = "\u00a0";
	public const string Softhyphen = "\u00ad";
}
